execution_engine: asyncio
logger:
  type: console
  level: info
  path: "./mcp-agent.log"

mcp:
  servers:
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "."]

openai:
  default_model: "anthropic/claude-3.7-sonnet"
  base_url: "https://openrouter.ai/api/v1"